language: rust
sudo: false

env:
  global:
    - secure: evQ5GzDM9Mw+P80iNSj4vvEaJ3QM8C46obNecQKxjfwsB1S0i3eE0BtSD+WkWV8C65epfdjakK69jLlb7qUx1RvDbIp8/UcxPUo7nJvXfBLuN+nVON2/khrzBMqFnRqqCsU4d4dQgSCMAoEf0l0mDY6VdKkysj1hbMj/Mau5OEI=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
